### ISSUE TITLE
s!game with optional arguments not working?

### ISSUE THREAD

**Issue by sacrophyte** [OfficialSirH/Semblance-bot#5]
Just curious, s!game is supposed to accept arguments, correct? Like s!game help, or s!game collect? When I try them, semblance ignores the arguments.

**Comment by OfficialSirH** [comment]
I removed the arguments from the command and replaced them with buttons so now it's only s!game. The new feature helps users with interacting with the bot without having to keep sending another message for another/repeated action.

**Comment by sacrophyte** [comment]
Sure, that makes sense. What about those of us who want the API-like functionality? :) Do both buttons and command-line arguments?

**Comment by OfficialSirH** [comment]
Having args for this command is problematic as users tend to fill the channel with lots of messages to keep collecting, which not only is a consistent filler of discord channels, but puts upon a lot of usage on Semblance, and isn't efficient.

**Comment by sacrophyte** [comment]
Ah, ok, thanks for providing more details.
